version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: DockerFiles/MsSql
      dockerfile: Dockerfile
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1534:1433"
    networks:
      - my_network

  lolusermanagerbeapi:
    image: ${DOCKER_REGISTRY-}lolusermanagerbeapi
    build:
      context: .
      dockerfile: LOLUserManagerBEApi/Dockerfile
    container_name: dotnet_app
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=TEST;User=sa;Password=YourStrong!Passw0rd;"
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge