version: '3.4'

services:
  lolusermanagerbeapi:
    image: ${DOCKER_REGISTRY-}lolusermanagerbeapi
    build:
      context: .
      dockerfile: LOLUserManagerBEApi/Dockerfile
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1534:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
    driver: local
